matches:
  - trigger: "wwe"
    replace: "ë"
  - trigger: "wwE"
    replace: "Ë"
  - trigger: "wwc"
    replace: "ç"
  - trigger: "wwC"
    replace: "Ç"
  
  # Alternative triggers
  - trigger: "qqe"
    replace: "ë"
  - trigger: "qqE"
    replace: "Ë"
  - trigger: "qqc"
    replace: "ç"
  - trigger: "qqC"
    replace: "Ç"

